### ISSUE TITLE
Update invoice doesn't work

### ISSUE THREAD

**Issue by alexmamonchik** [Invoiced/invoiced-ruby#1]
I have retrieved invoice.
```ruby
invoice = invoiced.Invoice.retrieve("{INVOICE_ID}")
```
try to update notes:
```ruby
invoice.notes = 'lol'
invoice.save
```
returns `true` but actually doesn't update invoice

**Comment by jaredtking** [comment]
Hey Alexander, thank you for catching this. It turns out the save method was halfway finished. My sincere apologies for that. I'm releasing a fix to address this in v0.0.4 of the gem.
