### ISSUE TITLE
Publish removal of activesupport dependency

### ISSUE THREAD

**Issue by raquelxmoss** [Invoiced/invoiced-ruby#10]
Hi! I notice you've committed some code to remove the dependency on ActiveSupport. Any chance you could publish this to RubyGems so that I can take advantage of the change? Thanks very much 😸

**Comment by jaredtking** [comment]
This is already true in v0.11+

**Comment by jaredtking** [comment]
Actually that removed dependency was not carried over to the published gem. We will get that corrected and update you here. Thanks!

**Comment by jaredtking** [comment]
Hi @raquelxmoss, the latest version (0.13) removes this dependency. Thanks again for reporting this.
