### ISSUE TITLE
send email to customer

### ISSUE THREAD

**Issue by alexmamonchik** [Invoiced/invoiced-ruby#2]
thanks for so fast response. One more thing.
in documentation I found way for sending invoice to customer:
```ruby
invoice.send
```
of course this is not working. I going to use this gem in my project. Can you help me with this issue?

**Comment by jaredtking** [comment]
Hey Alexander, sorry for the delay in getting back with you. We've just released v0.0.5 of this gem that now includes the invoice.send method. Please let us know if you bump into any more issues. Thanks for your patience as this client library is brand new so it is still a WIP.
