### ISSUE TITLE
date and due_date format

### ISSUE THREAD

**Issue by alexmamonchik** [Invoiced/invoiced-ruby#3]
When I create invoice I send:
```ruby
{
  date: "2015-10-06T18:00:00.000Z",
  due_date: 1445882400000
}
```
`date` saves correct but if change format for `date` to `1445882400000` it saves as `January 19, 2038`.

if change `due_date` to `2015-10-06T18:00:00.000Z` it saves as `January 1, 1970`

what is the correct format? In doc I see `timestamp` but that's wrong.

**Comment by jaredtking** [comment]
We represent all dates as Unix timestamps so please make sure you are
sending timestamps as integers.

On Oct 7, 2015, at 8:01 PM, Alexander Mamonchik <notifications@github.com>
wrote:

When I create invoice I send:

{
  date: "2015-10-06T18:00:00.000Z",
  due_date: 1445882400000
}

date saves correct but if change format for date to 1445882400000 it saves
as January 19, 2038.

if change due_date to 2015-10-06T18:00:00.000Z it saves as January 1, 1970

what is the correct format? In doc I see timestamp but that's wrong.

—
Reply to this email directly or view it on GitHub
<https://github.com/Invoiced/invoiced-ruby/issues/3>.
