### ISSUE TITLE
Does not support expanding related objects

### ISSUE THREAD

**Issue by MichaelDowse** [Invoiced/invoiced-ruby#4]
The Invoiced API supports expanding related objects (http://invoiced.com/docs/api/?ruby#special-parameters) to avoid having to make n additional queries for a query such as "All invoices and the associated customers".

Ideally the api for this would be something like:

```ruby
client.Invoice.list(expand: :customer)
```

**Comment by jaredtking** [comment]
Hey Michael! We do support expanding objects on the list endpoint. Actually your sample code was almost spot on. Here's how you expand customers when listing invoices:
```ruby
client.Invoice.list(:expand => "customer")
```
Does that work for you?

**Comment by MichaelDowse** [comment]
Oh excellent, thanks

**Comment by jaredtking** [comment]
Super belated follow up, but we updated the docs to include an example of expanding objects: http://invoiced.com/docs/api/?ruby#special-parameters
