### ISSUE TITLE
find Customer by

### ISSUE THREAD

**Issue by alexmamonchik** [Invoiced/invoiced-ruby#5]
Hi Jared. Will be fine to have some andpoint for retrieving customer by email, for example. But I see that email is not unique for customers.

**Comment by jaredtking** [comment]
Hi Alex! You should be able to do something like this:

```ruby
customers, metadata = invoiced.Customer.list(:filter => {'email' => 'hello@invoiced.com'})
```

You are correct in pointing out that email addresses are not required to be unique so please keep in mind that it's possible this call returns more than 1 customer (or none).

What are your thoughts?

**Comment by alexmamonchik** [comment]
that's a little bit confused. My real case:
I have 159 customers. But some customers IDs in my db had been lost and I have a lot of customers with the same details and part of them are garbage. I'll use filter for a next customer creation, thanks. I think, unique email allows data to be consistent.

**Comment by jaredtking** [comment]
Unfortunately we cannot enforce a unique constraint on customer emails as there are several legitimate use cases for creating multiple customers with the same email address. We appreciate the feedback though. If there's anything else we can do to help then please feel free to reach out.
