### ISSUE TITLE
Bundler could not find compatible versions for gem invoiced

### ISSUE THREAD

**Issue by ssmagin** [Invoiced/invoiced-ruby#7]
I'm using Invoiced gem with 
> ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
rails version
> Rails 5.1.2

When I run bundle install I got following error:

> Bundler could not find compatible versions for gem "activesupport":
>   In snapshot (Gemfile.lock):
>     activesupport (= 5.1.2)
> 
>   In Gemfile:
>     invoiced was resolved to 0.0.2, which depends on
>       activesupport (~> 4.2.3)
> 
>     rails (~> 5.1.2) was resolved to 5.1.2, which depends on
>       activesupport (= 5.1.2)
> 
>     rails (~> 5.1.2) was resolved to 5.1.2, which depends on
>       activesupport (= 5.1.2)
> 
>     rails (~> 5.1.2) was resolved to 5.1.2, which depends on
>       activesupport (= 5.1.2)
> 
>     rails (~> 5.1.2) was resolved to 5.1.2, which depends on
>       activesupport (= 5.1.2)
> 
>     rails (~> 5.1.2) was resolved to 5.1.2, which depends on
>       activesupport (= 5.1.2)
> 
>     rails (~> 5.1.2) was resolved to 5.1.2, which depends on
>       activesupport (= 5.1.2)
> 
>     rails (~> 5.1.2) was resolved to 5.1.2, which depends on
>       activesupport (= 5.1.2)
> 
> Running `bundle update` will rebuild your snapshot from scratch, using only
> the gems in your Gemfile, which may resolve the conflict.

Thank you!

**Comment by jaredtking** [comment]
Hm, that is frustrating. I think the activesupport dependency might be overkill. It adds a lot of baggage for the inflection function that we are using. I am going to look into removing activesuport from our gem and will let you know once that patch is available.

**Comment by jaredtking** [comment]
Can you try out PR #8? You can build the gem yourself with `gem build invoiced.gemspec` and then by running `gem install invoiced-0.12.0.gem`. Let me know if you are able to install the updated gem on your local machine.

**Comment by Putu-Widi84** [comment]
help me please
Bundler could not find compatible versions for gem
"activesupport":
  In Gemfile:
    wpscan was resolved to 3.3.2, which depends on
cms_scanner (~> 0.0.40.2) was resolved to 0.0.40.2, which
depends on
        activesupport (~> 4.2)

    wpscan was resolved to 3.3.2, which depends on
      activesupport (~> 5.2)
